### ISSUE TITLE
Multiple method calls in Api Explorer when only clicking Submit once.

### ISSUE THREAD

**Issue by traviswaldorf** [AmbitEnergyLabs/Nano#72] opened 2016-01-07 19:24 UTC
There is some unexpected behavior in the Api Explorer when submitting function calls. It seems to be related to entering in information for multiple methods or just expanding multiple methods. Even though one submit button is pressed, multiple calls are submitted.

**Comment by randyburden** [comment] 2016-01-08 03:50
Thanks for reporting this. We've already fixed this issue though and it will be included in the next upcoming release.

Here was the original reported issue is here: https://github.com/AmbitEnergyLabs/Nano/issues/67

And the commit that fixed the issue is here which is a one-liner fix: https://github.com/AmbitEnergyLabs/Nano/commit/a35da28243f3ae67e9d1612c5def0ce3550f2e0c

**Closed by randyburden** 2016-01-08 03:50 UTC
